name: Stars of the East
favicon: null
layout_spectrum: 0.8342707755509764
typography_spectrum: 0.5986419515684247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07284b'
    - '#f7f7f9'
    - '#26588d'
    - '#bdbab1'
    - '#7e5130'
  brandStrength: 0.04999652993865311
  lightness: 0.5938609603326768
  saturation: 0.5594491518568248
  rhythmicContrast: 0.9633041468914598
purpose: []
